package com.zippt.l3l4sa.common.validation;

public enum ValidationErrorCode {
    ID_INVALID,
    TEXT_LENGTH_INVALID,
    DECIMAL_RANGE_INVALID,
    DECIMAL_SCALE_INVALID,
    DATETIME_RANGE_INVALID,
    LICENSE_NUMBER_INVALID,
    OFFICE_REG_NO_INVALID,
    CREDENTIAL_STATUS_INVALID,
    AUCTION_DEADLINE_INVALID,
    CRITERIA_WEIGHT_INVALID,
    CRITERIA_PRIORITY_WEIGHT_INVALID,
    BID_COMMISSION_RATE_INVALID,
    BID_DUPLICATE_INVALID,
    RESERVATION_DUPLICATE_INVALID,
    RESERVATION_VISIT_AT_INVALID,
    REVIEW_RESERVATION_INVALID,
    REVIEW_DUPLICATE_INVALID,
    REVIEW_RATING_INVALID,
    NOTIFICATION_MESSAGE_INVALID,
    NOTIFICATION_STATUS_INVALID
}

